// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/stellarproject/nebula/agent/v1/agent.proto

package v1 // import "github.com/stellarproject/nebula/agent/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// skipping weak import gogoproto "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"

import time "time"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	Update               bool       `protobuf:"varint,2,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *CreateRequest) GetUpdate() bool {
	if m != nil {
		return m.Update
	}
	return false
}

type DeleteRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{1}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetResponse struct {
	Container            *ContainerInfo `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{3}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetContainer() *ContainerInfo {
	if m != nil {
		return m.Container
	}
	return nil
}

type KillRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Signal               uint32   `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillRequest) Reset()         { *m = KillRequest{} }
func (m *KillRequest) String() string { return proto.CompactTextString(m) }
func (*KillRequest) ProtoMessage()    {}
func (*KillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{4}
}
func (m *KillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillRequest.Unmarshal(m, b)
}
func (m *KillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillRequest.Marshal(b, m, deterministic)
}
func (dst *KillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillRequest.Merge(dst, src)
}
func (m *KillRequest) XXX_Size() int {
	return xxx_messageInfo_KillRequest.Size(m)
}
func (m *KillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillRequest proto.InternalMessageInfo

func (m *KillRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *KillRequest) GetSignal() uint32 {
	if m != nil {
		return m.Signal
	}
	return 0
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{5}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Containers           []*ContainerInfo `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{6}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetContainers() []*ContainerInfo {
	if m != nil {
		return m.Containers
	}
	return nil
}

type NodesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodesRequest) Reset()         { *m = NodesRequest{} }
func (m *NodesRequest) String() string { return proto.CompactTextString(m) }
func (*NodesRequest) ProtoMessage()    {}
func (*NodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{7}
}
func (m *NodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesRequest.Unmarshal(m, b)
}
func (m *NodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesRequest.Marshal(b, m, deterministic)
}
func (dst *NodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesRequest.Merge(dst, src)
}
func (m *NodesRequest) XXX_Size() int {
	return xxx_messageInfo_NodesRequest.Size(m)
}
func (m *NodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodesRequest proto.InternalMessageInfo

type NodesResponse struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodesResponse) Reset()         { *m = NodesResponse{} }
func (m *NodesResponse) String() string { return proto.CompactTextString(m) }
func (*NodesResponse) ProtoMessage()    {}
func (*NodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{8}
}
func (m *NodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesResponse.Unmarshal(m, b)
}
func (m *NodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesResponse.Marshal(b, m, deterministic)
}
func (dst *NodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesResponse.Merge(dst, src)
}
func (m *NodesResponse) XXX_Size() int {
	return xxx_messageInfo_NodesResponse.Size(m)
}
func (m *NodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodesResponse proto.InternalMessageInfo

func (m *NodesResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	ID                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Labels               map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{9}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ContainerInfo struct {
	ID                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string      `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Status               string      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	IP                   string      `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Cpu                  uint64      `protobuf:"varint,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryUsage          float64     `protobuf:"fixed64,6,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryLimit          float64     `protobuf:"fixed64,7,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	PidUsage             uint64      `protobuf:"varint,8,opt,name=pid_usage,json=pidUsage,proto3" json:"pid_usage,omitempty"`
	PidLimit             uint64      `protobuf:"varint,9,opt,name=pid_limit,json=pidLimit,proto3" json:"pid_limit,omitempty"`
	FsSize               int64       `protobuf:"varint,10,opt,name=fs_size,json=fsSize,proto3" json:"fs_size,omitempty"`
	Config               *Container  `protobuf:"bytes,11,opt,name=config" json:"config,omitempty"`
	Snapshots            []*Snapshot `protobuf:"bytes,12,rep,name=snapshots" json:"snapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContainerInfo) Reset()         { *m = ContainerInfo{} }
func (m *ContainerInfo) String() string { return proto.CompactTextString(m) }
func (*ContainerInfo) ProtoMessage()    {}
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{10}
}
func (m *ContainerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerInfo.Unmarshal(m, b)
}
func (m *ContainerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerInfo.Marshal(b, m, deterministic)
}
func (dst *ContainerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerInfo.Merge(dst, src)
}
func (m *ContainerInfo) XXX_Size() int {
	return xxx_messageInfo_ContainerInfo.Size(m)
}
func (m *ContainerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerInfo proto.InternalMessageInfo

func (m *ContainerInfo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ContainerInfo) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ContainerInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ContainerInfo) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ContainerInfo) GetCpu() uint64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *ContainerInfo) GetMemoryUsage() float64 {
	if m != nil {
		return m.MemoryUsage
	}
	return 0
}

func (m *ContainerInfo) GetMemoryLimit() float64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

func (m *ContainerInfo) GetPidUsage() uint64 {
	if m != nil {
		return m.PidUsage
	}
	return 0
}

func (m *ContainerInfo) GetPidLimit() uint64 {
	if m != nil {
		return m.PidLimit
	}
	return 0
}

func (m *ContainerInfo) GetFsSize() int64 {
	if m != nil {
		return m.FsSize
	}
	return 0
}

func (m *ContainerInfo) GetConfig() *Container {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ContainerInfo) GetSnapshots() []*Snapshot {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

type Snapshot struct {
	ID                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              time.Time `protobuf:"bytes,2,opt,name=created,stdtime" json:"created"`
	Previous             string    `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	FsSize               int64     `protobuf:"varint,4,opt,name=fs_size,json=fsSize,proto3" json:"fs_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{11}
}
func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (dst *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(dst, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Snapshot) GetCreated() time.Time {
	if m != nil {
		return m.Created
	}
	return time.Time{}
}

func (m *Snapshot) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *Snapshot) GetFsSize() int64 {
	if m != nil {
		return m.FsSize
	}
	return 0
}

type RollbackRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackRequest) Reset()         { *m = RollbackRequest{} }
func (m *RollbackRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackRequest) ProtoMessage()    {}
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{12}
}
func (m *RollbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackRequest.Unmarshal(m, b)
}
func (m *RollbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackRequest.Marshal(b, m, deterministic)
}
func (dst *RollbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackRequest.Merge(dst, src)
}
func (m *RollbackRequest) XXX_Size() int {
	return xxx_messageInfo_RollbackRequest.Size(m)
}
func (m *RollbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackRequest proto.InternalMessageInfo

func (m *RollbackRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type RollbackResponse struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RollbackResponse) Reset()         { *m = RollbackResponse{} }
func (m *RollbackResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackResponse) ProtoMessage()    {}
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{13}
}
func (m *RollbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackResponse.Unmarshal(m, b)
}
func (m *RollbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackResponse.Marshal(b, m, deterministic)
}
func (dst *RollbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackResponse.Merge(dst, src)
}
func (m *RollbackResponse) XXX_Size() int {
	return xxx_messageInfo_RollbackResponse.Size(m)
}
func (m *RollbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackResponse proto.InternalMessageInfo

func (m *RollbackResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type StartRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{14}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type StopRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{15}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UpdateRequest struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{16}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type UpdateResponse struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{17}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type PushRequest struct {
	Ref                  string   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Build                bool     `protobuf:"varint,2,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{18}
}
func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (dst *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(dst, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *PushRequest) GetBuild() bool {
	if m != nil {
		return m.Build
	}
	return false
}

type CheckpointRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Live                 bool     `protobuf:"varint,3,opt,name=live,proto3" json:"live,omitempty"`
	Exit                 bool     `protobuf:"varint,4,opt,name=exit,proto3" json:"exit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckpointRequest) Reset()         { *m = CheckpointRequest{} }
func (m *CheckpointRequest) String() string { return proto.CompactTextString(m) }
func (*CheckpointRequest) ProtoMessage()    {}
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{19}
}
func (m *CheckpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckpointRequest.Unmarshal(m, b)
}
func (m *CheckpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckpointRequest.Marshal(b, m, deterministic)
}
func (dst *CheckpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointRequest.Merge(dst, src)
}
func (m *CheckpointRequest) XXX_Size() int {
	return xxx_messageInfo_CheckpointRequest.Size(m)
}
func (m *CheckpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointRequest proto.InternalMessageInfo

func (m *CheckpointRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CheckpointRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *CheckpointRequest) GetLive() bool {
	if m != nil {
		return m.Live
	}
	return false
}

func (m *CheckpointRequest) GetExit() bool {
	if m != nil {
		return m.Exit
	}
	return false
}

type CheckpointResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckpointResponse) Reset()         { *m = CheckpointResponse{} }
func (m *CheckpointResponse) String() string { return proto.CompactTextString(m) }
func (*CheckpointResponse) ProtoMessage()    {}
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{20}
}
func (m *CheckpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckpointResponse.Unmarshal(m, b)
}
func (m *CheckpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckpointResponse.Marshal(b, m, deterministic)
}
func (dst *CheckpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointResponse.Merge(dst, src)
}
func (m *CheckpointResponse) XXX_Size() int {
	return xxx_messageInfo_CheckpointResponse.Size(m)
}
func (m *CheckpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointResponse proto.InternalMessageInfo

type RestoreRequest struct {
	Ref                  string   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Live                 bool     `protobuf:"varint,2,opt,name=live,proto3" json:"live,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{21}
}
func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (dst *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(dst, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

func (m *RestoreRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *RestoreRequest) GetLive() bool {
	if m != nil {
		return m.Live
	}
	return false
}

type RestoreResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreResponse) Reset()         { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()    {}
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{22}
}
func (m *RestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResponse.Unmarshal(m, b)
}
func (m *RestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResponse.Marshal(b, m, deterministic)
}
func (dst *RestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResponse.Merge(dst, src)
}
func (m *RestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreResponse.Size(m)
}
func (m *RestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResponse proto.InternalMessageInfo

type MigrateRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Live                 bool     `protobuf:"varint,3,opt,name=live,proto3" json:"live,omitempty"`
	Stop                 bool     `protobuf:"varint,4,opt,name=stop,proto3" json:"stop,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Delete               bool     `protobuf:"varint,6,opt,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateRequest) Reset()         { *m = MigrateRequest{} }
func (m *MigrateRequest) String() string { return proto.CompactTextString(m) }
func (*MigrateRequest) ProtoMessage()    {}
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{23}
}
func (m *MigrateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateRequest.Unmarshal(m, b)
}
func (m *MigrateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateRequest.Marshal(b, m, deterministic)
}
func (dst *MigrateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateRequest.Merge(dst, src)
}
func (m *MigrateRequest) XXX_Size() int {
	return xxx_messageInfo_MigrateRequest.Size(m)
}
func (m *MigrateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateRequest proto.InternalMessageInfo

func (m *MigrateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MigrateRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *MigrateRequest) GetLive() bool {
	if m != nil {
		return m.Live
	}
	return false
}

func (m *MigrateRequest) GetStop() bool {
	if m != nil {
		return m.Stop
	}
	return false
}

func (m *MigrateRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MigrateRequest) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

type MigrateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateResponse) Reset()         { *m = MigrateResponse{} }
func (m *MigrateResponse) String() string { return proto.CompactTextString(m) }
func (*MigrateResponse) ProtoMessage()    {}
func (*MigrateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{24}
}
func (m *MigrateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateResponse.Unmarshal(m, b)
}
func (m *MigrateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateResponse.Marshal(b, m, deterministic)
}
func (dst *MigrateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateResponse.Merge(dst, src)
}
func (m *MigrateResponse) XXX_Size() int {
	return xxx_messageInfo_MigrateResponse.Size(m)
}
func (m *MigrateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateResponse proto.InternalMessageInfo

type Container struct {
	ID                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string              `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Network              string              `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Process              *Process            `protobuf:"bytes,4,opt,name=process" json:"process,omitempty"`
	Mounts               []*Mount            `protobuf:"bytes,5,rep,name=mounts" json:"mounts,omitempty"`
	Resources            *Resources          `protobuf:"bytes,6,opt,name=resources" json:"resources,omitempty"`
	Gpus                 *GPUs               `protobuf:"bytes,7,opt,name=gpus" json:"gpus,omitempty"`
	Services             map[string]*Service `protobuf:"bytes,8,rep,name=services" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	Configs              map[string]*Config  `protobuf:"bytes,9,rep,name=configs" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	Readonly             bool                `protobuf:"varint,10,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Volumes              []*Volume           `protobuf:"bytes,11,rep,name=volumes" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{25}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Container) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Container) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Container) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *Container) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Container) GetGpus() *GPUs {
	if m != nil {
		return m.Gpus
	}
	return nil
}

func (m *Container) GetServices() map[string]*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Container) GetConfigs() map[string]*Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

func (m *Container) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

func (m *Container) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type Volume struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Rw                   bool     `protobuf:"varint,3,opt,name=rw,proto3" json:"rw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{26}
}
func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (dst *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(dst, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Volume) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Volume) GetRw() bool {
	if m != nil {
		return m.Rw
	}
	return false
}

type Config struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Signal               string   `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{27}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Config) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Config) GetSignal() string {
	if m != nil {
		return m.Signal
	}
	return ""
}

func (m *Config) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Service struct {
	Port                 int64        `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Labels               []string     `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty"`
	Url                  string       `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Check                *HealthCheck `protobuf:"bytes,4,opt,name=check" json:"check,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{28}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Service) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Service) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Service) GetCheck() *HealthCheck {
	if m != nil {
		return m.Check
	}
	return nil
}

type HealthCheck struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Interval             int64    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout              int64    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheck) Reset()         { *m = HealthCheck{} }
func (m *HealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheck) ProtoMessage()    {}
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{29}
}
func (m *HealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheck.Unmarshal(m, b)
}
func (m *HealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheck.Marshal(b, m, deterministic)
}
func (dst *HealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheck.Merge(dst, src)
}
func (m *HealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheck.Size(m)
}
func (m *HealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheck proto.InternalMessageInfo

func (m *HealthCheck) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HealthCheck) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *HealthCheck) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *HealthCheck) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type GPUs struct {
	Devices              []int64  `protobuf:"varint,1,rep,packed,name=devices" json:"devices,omitempty"`
	Capabilities         []string `protobuf:"bytes,2,rep,name=capabilities" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPUs) Reset()         { *m = GPUs{} }
func (m *GPUs) String() string { return proto.CompactTextString(m) }
func (*GPUs) ProtoMessage()    {}
func (*GPUs) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{30}
}
func (m *GPUs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPUs.Unmarshal(m, b)
}
func (m *GPUs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPUs.Marshal(b, m, deterministic)
}
func (dst *GPUs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUs.Merge(dst, src)
}
func (m *GPUs) XXX_Size() int {
	return xxx_messageInfo_GPUs.Size(m)
}
func (m *GPUs) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUs.DiscardUnknown(m)
}

var xxx_messageInfo_GPUs proto.InternalMessageInfo

func (m *GPUs) GetDevices() []int64 {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *GPUs) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type Resources struct {
	Cpus                 float64  `protobuf:"fixed64,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory               int64    `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Score                int64    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	NoFile               uint64   `protobuf:"varint,4,opt,name=no_file,json=noFile,proto3" json:"no_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{31}
}
func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (dst *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(dst, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetCpus() float64 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *Resources) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Resources) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Resources) GetNoFile() uint64 {
	if m != nil {
		return m.NoFile
	}
	return 0
}

type Mount struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Options              []string `protobuf:"bytes,4,rep,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{32}
}
func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (dst *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(dst, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Mount) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Mount) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Mount) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type Process struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	Env                  []string `protobuf:"bytes,3,rep,name=env" json:"env,omitempty"`
	Capabilities         []string `protobuf:"bytes,4,rep,name=capabilities" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{33}
}
func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (dst *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(dst, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Process) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Process) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Process) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type User struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_212c53d802e00be9, []int{34}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "io.stellarproject.v1.CreateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "io.stellarproject.v1.DeleteRequest")
	proto.RegisterType((*GetRequest)(nil), "io.stellarproject.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "io.stellarproject.v1.GetResponse")
	proto.RegisterType((*KillRequest)(nil), "io.stellarproject.v1.KillRequest")
	proto.RegisterType((*ListRequest)(nil), "io.stellarproject.v1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "io.stellarproject.v1.ListResponse")
	proto.RegisterType((*NodesRequest)(nil), "io.stellarproject.v1.NodesRequest")
	proto.RegisterType((*NodesResponse)(nil), "io.stellarproject.v1.NodesResponse")
	proto.RegisterType((*Node)(nil), "io.stellarproject.v1.Node")
	proto.RegisterMapType((map[string]string)(nil), "io.stellarproject.v1.Node.LabelsEntry")
	proto.RegisterType((*ContainerInfo)(nil), "io.stellarproject.v1.ContainerInfo")
	proto.RegisterType((*Snapshot)(nil), "io.stellarproject.v1.Snapshot")
	proto.RegisterType((*RollbackRequest)(nil), "io.stellarproject.v1.RollbackRequest")
	proto.RegisterType((*RollbackResponse)(nil), "io.stellarproject.v1.RollbackResponse")
	proto.RegisterType((*StartRequest)(nil), "io.stellarproject.v1.StartRequest")
	proto.RegisterType((*StopRequest)(nil), "io.stellarproject.v1.StopRequest")
	proto.RegisterType((*UpdateRequest)(nil), "io.stellarproject.v1.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "io.stellarproject.v1.UpdateResponse")
	proto.RegisterType((*PushRequest)(nil), "io.stellarproject.v1.PushRequest")
	proto.RegisterType((*CheckpointRequest)(nil), "io.stellarproject.v1.CheckpointRequest")
	proto.RegisterType((*CheckpointResponse)(nil), "io.stellarproject.v1.CheckpointResponse")
	proto.RegisterType((*RestoreRequest)(nil), "io.stellarproject.v1.RestoreRequest")
	proto.RegisterType((*RestoreResponse)(nil), "io.stellarproject.v1.RestoreResponse")
	proto.RegisterType((*MigrateRequest)(nil), "io.stellarproject.v1.MigrateRequest")
	proto.RegisterType((*MigrateResponse)(nil), "io.stellarproject.v1.MigrateResponse")
	proto.RegisterType((*Container)(nil), "io.stellarproject.v1.Container")
	proto.RegisterMapType((map[string]*Config)(nil), "io.stellarproject.v1.Container.ConfigsEntry")
	proto.RegisterMapType((map[string]*Service)(nil), "io.stellarproject.v1.Container.ServicesEntry")
	proto.RegisterType((*Volume)(nil), "io.stellarproject.v1.Volume")
	proto.RegisterType((*Config)(nil), "io.stellarproject.v1.Config")
	proto.RegisterType((*Service)(nil), "io.stellarproject.v1.Service")
	proto.RegisterType((*HealthCheck)(nil), "io.stellarproject.v1.HealthCheck")
	proto.RegisterType((*GPUs)(nil), "io.stellarproject.v1.GPUs")
	proto.RegisterType((*Resources)(nil), "io.stellarproject.v1.Resources")
	proto.RegisterType((*Mount)(nil), "io.stellarproject.v1.Mount")
	proto.RegisterType((*Process)(nil), "io.stellarproject.v1.Process")
	proto.RegisterType((*User)(nil), "io.stellarproject.v1.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*types.Empty, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error)
	Nodes(ctx context.Context, in *NodesRequest, opts ...grpc.CallOption) (*NodesResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Kill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Rollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Checkpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error) {
	out := new(MigrateResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Migrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Nodes(ctx context.Context, in *NodesRequest, opts ...grpc.CallOption) (*NodesResponse, error) {
	out := new(NodesResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.v1.Agent/Nodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Create(context.Context, *CreateRequest) (*types.Empty, error)
	Delete(context.Context, *DeleteRequest) (*types.Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Kill(context.Context, *KillRequest) (*types.Empty, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	Start(context.Context, *StartRequest) (*types.Empty, error)
	Stop(context.Context, *StopRequest) (*types.Empty, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Push(context.Context, *PushRequest) (*types.Empty, error)
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	Migrate(context.Context, *MigrateRequest) (*MigrateResponse, error)
	Nodes(context.Context, *NodesRequest) (*NodesResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Kill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Rollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Checkpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Migrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Nodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Nodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.v1.Agent/Nodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Nodes(ctx, req.(*NodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.stellarproject.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Agent_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Agent_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Agent_Get_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _Agent_Kill_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Agent_List_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _Agent_Rollback_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Agent_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Agent_Stop_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Agent_Update_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _Agent_Push_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _Agent_Checkpoint_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Agent_Restore_Handler,
		},
		{
			MethodName: "Migrate",
			Handler:    _Agent_Migrate_Handler,
		},
		{
			MethodName: "Nodes",
			Handler:    _Agent_Nodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/stellarproject/nebula/agent/v1/agent.proto",
}

func init() {
	proto.RegisterFile("github.com/stellarproject/nebula/agent/v1/agent.proto", fileDescriptor_agent_212c53d802e00be9)
}

var fileDescriptor_agent_212c53d802e00be9 = []byte{
	// 1645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x72, 0x1b, 0xb9,
	0x11, 0xde, 0xe1, 0x3f, 0x9b, 0xa2, 0xd6, 0x8b, 0x52, 0x39, 0x53, 0xf4, 0x26, 0xa2, 0x67, 0x6d,
	0xaf, 0x92, 0xda, 0x50, 0xb1, 0x5d, 0xbb, 0xce, 0xdf, 0x6e, 0x95, 0x2c, 0xff, 0xc4, 0x89, 0xed,
	0x28, 0x50, 0xe4, 0x72, 0x7c, 0x51, 0x0d, 0x39, 0x20, 0x85, 0x68, 0x38, 0x98, 0x0c, 0x30, 0x74,
	0xe4, 0x53, 0xaa, 0x72, 0xcb, 0x25, 0xb9, 0xe5, 0x41, 0xf2, 0x12, 0xb9, 0xe4, 0x90, 0x17, 0x70,
	0xaa, 0xf2, 0x24, 0xa9, 0x06, 0x30, 0xe4, 0x50, 0x22, 0x44, 0xa5, 0xd6, 0xb7, 0x6e, 0xf0, 0x43,
	0xf7, 0xd7, 0x98, 0x46, 0xa3, 0x9b, 0xf0, 0xe5, 0x84, 0xab, 0x93, 0x7c, 0x38, 0x18, 0x89, 0xe9,
	0xae, 0x54, 0x2c, 0x8e, 0xc3, 0x2c, 0xcd, 0xc4, 0xef, 0xd9, 0x48, 0xed, 0x26, 0x6c, 0x98, 0xc7,
	0xe1, 0x6e, 0x38, 0x61, 0x89, 0xda, 0x9d, 0xdd, 0x35, 0xc2, 0x20, 0xcd, 0x84, 0x12, 0x64, 0x8b,
	0x8b, 0xc1, 0x32, 0x7c, 0x30, 0xbb, 0xdb, 0xdb, 0x9a, 0x88, 0x89, 0xd0, 0x80, 0x5d, 0x94, 0x0c,
	0xb6, 0x77, 0x63, 0x22, 0xc4, 0x24, 0x66, 0xbb, 0x5a, 0x1b, 0xe6, 0xe3, 0x5d, 0x36, 0x4d, 0xd5,
	0x99, 0xfd, 0x71, 0xfb, 0xfc, 0x8f, 0x8a, 0x4f, 0x99, 0x54, 0xe1, 0x34, 0x35, 0x80, 0x60, 0x0c,
	0xdd, 0xfd, 0x8c, 0x85, 0x8a, 0x51, 0xf6, 0x87, 0x9c, 0x49, 0x45, 0xbe, 0x86, 0xf6, 0x48, 0x24,
	0x2a, 0xe4, 0x09, 0xcb, 0x7c, 0xaf, 0xef, 0xed, 0x74, 0xee, 0x6d, 0x0f, 0x56, 0xd1, 0x19, 0xec,
	0x17, 0x30, 0xba, 0xd8, 0x41, 0xae, 0x43, 0x23, 0x4f, 0xa3, 0x50, 0x31, 0xbf, 0xd2, 0xf7, 0x76,
	0x5a, 0xd4, 0x6a, 0xc1, 0xe7, 0xd0, 0x7d, 0xc4, 0x62, 0xb6, 0xf0, 0x73, 0x1d, 0x2a, 0x3c, 0xd2,
	0x0e, 0xda, 0x0f, 0x1b, 0xff, 0x7d, 0xbf, 0x5d, 0x79, 0xf6, 0x88, 0x56, 0x78, 0x14, 0xdc, 0x02,
	0x78, 0xca, 0xd4, 0x3a, 0xd4, 0x01, 0x74, 0x34, 0x4a, 0xa6, 0x22, 0x91, 0x8c, 0xec, 0x5d, 0x24,
	0xfd, 0xd9, 0x1a, 0xd2, 0xcf, 0x92, 0xb1, 0x28, 0x11, 0x0f, 0xbe, 0x86, 0xce, 0xaf, 0x78, 0x1c,
	0xaf, 0x71, 0x8c, 0xf1, 0x49, 0x3e, 0x49, 0xc2, 0x58, 0xc7, 0xd7, 0xa5, 0x56, 0x0b, 0xba, 0xd0,
	0x79, 0xce, 0x65, 0xc1, 0x3b, 0x38, 0x84, 0x0d, 0xa3, 0x5a, 0x82, 0xfb, 0x00, 0x73, 0x57, 0xd2,
	0xf7, 0xfa, 0xd5, 0xab, 0x32, 0x2c, 0x6d, 0x0b, 0x36, 0x61, 0xe3, 0xa5, 0x88, 0x98, 0x2c, 0x9c,
	0xec, 0x41, 0xd7, 0xea, 0xd6, 0xcb, 0x8f, 0xa0, 0x9e, 0xe0, 0x82, 0x75, 0xd0, 0x5b, 0xed, 0x00,
	0xf7, 0x50, 0x03, 0x0c, 0xfe, 0xe1, 0x41, 0x0d, 0x75, 0x67, 0xbc, 0x3e, 0x34, 0xc3, 0x28, 0xca,
	0x98, 0x94, 0x3a, 0xe0, 0x36, 0x2d, 0x54, 0xf2, 0x0d, 0x34, 0xe2, 0x70, 0xc8, 0x62, 0xe9, 0x57,
	0xb5, 0xb7, 0x3b, 0x6e, 0x6f, 0x83, 0xe7, 0x1a, 0xf8, 0x38, 0x51, 0xd9, 0x19, 0xb5, 0xbb, 0x7a,
	0x3f, 0x81, 0x4e, 0x69, 0x99, 0x5c, 0x83, 0xea, 0x29, 0x3b, 0x33, 0x0c, 0x28, 0x8a, 0x64, 0x0b,
	0xea, 0xb3, 0x30, 0xce, 0x99, 0x75, 0x6c, 0x94, 0x9f, 0x56, 0x7e, 0xec, 0x05, 0x7f, 0xad, 0x42,
	0x77, 0xe9, 0x98, 0x9c, 0xf4, 0xb7, 0xa0, 0xce, 0xa7, 0xe1, 0x64, 0x6e, 0x43, 0x2b, 0xfa, 0x23,
	0xaa, 0x50, 0xe5, 0x48, 0x1d, 0x97, 0xad, 0xa6, 0xad, 0xa4, 0x7e, 0xad, 0x64, 0xe5, 0x80, 0x56,
	0x78, 0x8a, 0xdc, 0x46, 0x69, 0xee, 0xd7, 0xfb, 0xde, 0x4e, 0x8d, 0xa2, 0x48, 0x6e, 0xc2, 0xc6,
	0x94, 0x4d, 0x45, 0x76, 0x76, 0x9c, 0x4b, 0x34, 0xdf, 0xe8, 0x7b, 0x3b, 0x1e, 0xed, 0x98, 0xb5,
	0x23, 0x5c, 0x2a, 0x41, 0x62, 0x3e, 0xe5, 0xca, 0x6f, 0x96, 0x21, 0xcf, 0x71, 0x89, 0xdc, 0x80,
	0x76, 0xca, 0x23, 0x6b, 0xa2, 0xa5, 0xad, 0xb7, 0x52, 0x1e, 0x99, 0xfd, 0xf6, 0x47, 0xb3, 0xb9,
	0x3d, 0xff, 0xd1, 0xec, 0xfc, 0x0e, 0x34, 0xc7, 0xf2, 0x58, 0xf2, 0x77, 0xcc, 0x87, 0xbe, 0xb7,
	0x53, 0xa5, 0x8d, 0xb1, 0x3c, 0xe4, 0xef, 0x18, 0x79, 0x00, 0x8d, 0x91, 0x48, 0xc6, 0x7c, 0xe2,
	0x77, 0xae, 0x76, 0x77, 0x2d, 0x9c, 0xfc, 0x1c, 0xda, 0x32, 0x09, 0x53, 0x79, 0x22, 0x94, 0xf4,
	0x37, 0xf4, 0x17, 0xfd, 0xde, 0xea, 0xbd, 0x87, 0x16, 0x46, 0x17, 0x1b, 0x82, 0xbf, 0x7b, 0xd0,
	0x2a, 0xd6, 0x9d, 0x1f, 0xe3, 0x1b, 0x68, 0x8e, 0x74, 0xad, 0x89, 0xf4, 0xe7, 0xc0, 0x04, 0x35,
	0xe5, 0x69, 0x50, 0x94, 0xa7, 0xc1, 0x6f, 0x8b, 0xf2, 0xf4, 0xb0, 0xf5, 0xcf, 0xf7, 0xdb, 0x1f,
	0xfd, 0xed, 0x3f, 0xdb, 0x1e, 0x2d, 0x36, 0x91, 0x1e, 0xb4, 0xd2, 0x8c, 0xcd, 0xb8, 0x98, 0x7f,
	0xb8, 0xb9, 0x5e, 0x3e, 0x90, 0x5a, 0xf9, 0x40, 0x82, 0xef, 0xc3, 0xc7, 0x54, 0xc4, 0xf1, 0x30,
	0x1c, 0x9d, 0xae, 0x2b, 0x2a, 0xbf, 0x81, 0x6b, 0x0b, 0xa8, 0xbd, 0x52, 0xdf, 0xae, 0x1c, 0x06,
	0x77, 0x60, 0xe3, 0x50, 0x85, 0xd9, 0xda, 0x7a, 0x76, 0x1b, 0x3a, 0x87, 0x4a, 0xa4, 0xeb, 0x60,
	0x2f, 0xa1, 0x7b, 0xa4, 0xeb, 0xe9, 0x87, 0xa9, 0xd6, 0xc1, 0xaf, 0x61, 0xb3, 0xb0, 0xf7, 0x61,
	0xe2, 0xfd, 0x12, 0x3a, 0x07, 0xb9, 0x3c, 0x29, 0xe8, 0x5d, 0x83, 0x6a, 0xc6, 0xc6, 0xc5, 0xa5,
	0xce, 0xd8, 0x18, 0x2f, 0xe4, 0x30, 0xe7, 0x71, 0x64, 0x9f, 0x07, 0xa3, 0x04, 0x0c, 0x3e, 0xd9,
	0x3f, 0x61, 0xa3, 0xd3, 0x54, 0xf0, 0x64, 0xdd, 0x59, 0x15, 0x46, 0x2b, 0x0b, 0xa3, 0x04, 0x6a,
	0x31, 0x9f, 0x31, 0x9d, 0x14, 0x2d, 0xaa, 0x65, 0x5c, 0x63, 0x7f, 0xe4, 0x4a, 0x67, 0x43, 0x8b,
	0x6a, 0x39, 0xd8, 0x02, 0x52, 0x76, 0x63, 0x42, 0x0e, 0xbe, 0x82, 0x4d, 0xca, 0xa4, 0x12, 0x19,
	0x73, 0xd3, 0x2e, 0x3c, 0x54, 0x16, 0x1e, 0x82, 0x4f, 0xe0, 0xe3, 0xf9, 0x3e, 0x6b, 0xea, 0x2f,
	0x1e, 0x6c, 0xbe, 0xe0, 0x93, 0x2c, 0x5c, 0xfb, 0xce, 0x5d, 0x3d, 0x0a, 0xa9, 0x44, 0x5a, 0x44,
	0x81, 0x32, 0xd9, 0x84, 0x8a, 0x12, 0xba, 0x18, 0xb5, 0x69, 0x45, 0x61, 0xed, 0x6b, 0x44, 0xfa,
	0x69, 0xd5, 0x55, 0xa8, 0x45, 0xad, 0x86, 0xfc, 0xe6, 0x5c, 0x2c, 0xbf, 0x7f, 0xd5, 0xa1, 0xbd,
	0x5f, 0x7a, 0xab, 0xff, 0x9f, 0xa2, 0xe9, 0x43, 0x33, 0x61, 0xea, 0xad, 0xc8, 0x4e, 0xed, 0xe5,
	0x2b, 0x54, 0xf2, 0x00, 0x9a, 0x69, 0x26, 0x46, 0xf8, 0x46, 0xd4, 0x74, 0xc6, 0x7c, 0x77, 0x75,
	0xc6, 0x1c, 0x18, 0x10, 0x2d, 0xd0, 0xe4, 0x3e, 0x34, 0xa6, 0x22, 0x4f, 0x94, 0xf4, 0xeb, 0xba,
	0xe0, 0xdc, 0x58, 0xbd, 0xef, 0x05, 0x62, 0xa8, 0x85, 0x62, 0x86, 0x66, 0x4c, 0x8a, 0x3c, 0x1b,
	0x31, 0xa9, 0x23, 0x76, 0x66, 0x28, 0x2d, 0x60, 0x74, 0xb1, 0x83, 0x0c, 0xa0, 0x36, 0x49, 0x73,
	0xa9, 0xcb, 0xb1, 0xf3, 0x89, 0x7c, 0x7a, 0x70, 0x24, 0xa9, 0xc6, 0x91, 0x67, 0xd0, 0x92, 0x2c,
	0x9b, 0x71, 0xf4, 0xd6, 0xd2, 0x2c, 0x7f, 0xb8, 0xe6, 0x3e, 0x0c, 0x0e, 0x2d, 0xde, 0xbc, 0x77,
	0xf3, 0xed, 0xe4, 0x09, 0x34, 0x4d, 0xb1, 0x95, 0x7e, 0x5b, 0x5b, 0xfa, 0x62, 0x9d, 0xa5, 0x7d,
	0x03, 0x37, 0x86, 0x8a, 0xcd, 0x58, 0x07, 0x33, 0x16, 0x46, 0x22, 0x89, 0xcf, 0x74, 0xf5, 0x6f,
	0xd1, 0xb9, 0x4e, 0xbe, 0x82, 0xe6, 0x4c, 0xc4, 0xf9, 0x94, 0x49, 0xbf, 0xa3, 0x7d, 0x7c, 0xba,
	0xda, 0xc7, 0x2b, 0x0d, 0xa2, 0x05, 0xb8, 0xf7, 0x06, 0xba, 0x4b, 0xb4, 0x57, 0xbc, 0xc7, 0xf7,
	0xcb, 0xef, 0xb1, 0xf3, 0x23, 0x5b, 0x2b, 0xa5, 0xe7, 0xba, 0xf7, 0x1a, 0x36, 0xca, 0x81, 0xac,
	0x30, 0x7d, 0x6f, 0xd9, 0xf4, 0xa7, 0xce, 0x73, 0x19, 0xf3, 0x49, 0xb9, 0x11, 0xa0, 0xd0, 0x30,
	0x81, 0x38, 0x73, 0xb9, 0x0f, 0x9d, 0x88, 0x49, 0xc5, 0x93, 0x50, 0x71, 0x91, 0xd8, 0x8c, 0x2e,
	0x2f, 0xe1, 0x75, 0xca, 0xde, 0xda, 0x4b, 0x57, 0xc9, 0xde, 0x06, 0x63, 0x68, 0x18, 0x47, 0x78,
	0xf9, 0xd2, 0x50, 0x9d, 0x58, 0xa2, 0x5a, 0xd6, 0xad, 0x83, 0xce, 0x24, 0x6b, 0xca, 0x6a, 0xa5,
	0xbe, 0xb0, 0x68, 0x29, 0xb4, 0x86, 0xb7, 0x06, 0xab, 0x23, 0x4b, 0x4c, 0x25, 0x6a, 0xd3, 0x42,
	0x0d, 0xfe, 0xe4, 0x41, 0xd3, 0x1e, 0x96, 0xf6, 0x24, 0x32, 0xa5, 0x3d, 0x55, 0xa9, 0x96, 0xd1,
	0xa2, 0xed, 0xaf, 0x2a, 0xfd, 0x2a, 0x5a, 0x34, 0x1a, 0x9e, 0x5e, 0x9e, 0x15, 0x6e, 0x50, 0x24,
	0x0f, 0xa0, 0x3e, 0xc2, 0xb2, 0x66, 0x6f, 0xdf, 0xcd, 0xd5, 0xa7, 0xf7, 0x0b, 0x16, 0xc6, 0xea,
	0x44, 0xd7, 0x3f, 0x6a, 0xf0, 0x81, 0x80, 0x4e, 0x69, 0x15, 0x59, 0xa8, 0xb3, 0x94, 0x15, 0xf1,
	0xa2, 0x8c, 0xb9, 0xc6, 0x13, 0xc5, 0xb2, 0x99, 0xed, 0x78, 0xab, 0x74, 0xae, 0x63, 0x6c, 0x38,
	0x4e, 0x88, 0x5c, 0x69, 0x36, 0x55, 0x5a, 0xa8, 0xc8, 0x7d, 0xca, 0xd4, 0x89, 0x88, 0x6c, 0xd0,
	0x56, 0x0b, 0x1e, 0x41, 0x0d, 0xaf, 0x16, 0xee, 0x8c, 0x98, 0xb9, 0x53, 0xd8, 0xaa, 0x56, 0x69,
	0xa1, 0x92, 0x00, 0x36, 0x46, 0x61, 0x1a, 0x0e, 0x79, 0xcc, 0x15, 0x67, 0x45, 0xec, 0x4b, 0x6b,
	0xc1, 0x18, 0xda, 0xf3, 0xab, 0x8d, 0xa4, 0x47, 0x78, 0x9f, 0x3d, 0xdd, 0x5e, 0x69, 0xd9, 0xb8,
	0xc7, 0x36, 0xcb, 0x52, 0xb6, 0x1a, 0x16, 0x36, 0x39, 0x12, 0x19, 0xb3, 0x74, 0x8d, 0x82, 0xad,
	0x43, 0x22, 0x8e, 0xc7, 0x3c, 0x36, 0xad, 0x43, 0x8d, 0x36, 0x12, 0xf1, 0x84, 0xc7, 0x2c, 0x10,
	0x50, 0xd7, 0xa5, 0x67, 0xe5, 0xc1, 0xb8, 0x12, 0xe1, 0x5c, 0xc2, 0x55, 0x2f, 0x26, 0x9c, 0x0f,
	0x4d, 0x91, 0xa2, 0x84, 0xe5, 0x12, 0xa3, 0x2b, 0xd4, 0xe0, 0xcf, 0x1e, 0x34, 0x6d, 0x91, 0xc4,
	0x3a, 0x95, 0xcb, 0xf9, 0x1b, 0xec, 0xa8, 0x53, 0x47, 0x92, 0x65, 0x54, 0xe3, 0x90, 0x63, 0x98,
	0x4d, 0x8a, 0x03, 0xd3, 0x32, 0xa6, 0x0a, 0x4b, 0x66, 0xba, 0x3f, 0x6f, 0x53, 0x14, 0x2f, 0x1c,
	0x6f, 0x6d, 0xc5, 0xf1, 0xfe, 0x00, 0x6a, 0x68, 0x57, 0x27, 0x9a, 0xbd, 0x53, 0x5d, 0x8a, 0x22,
	0xae, 0x4c, 0x78, 0x64, 0x27, 0x1f, 0x14, 0xef, 0xfd, 0xbb, 0x05, 0xf5, 0x3d, 0x1c, 0x5c, 0xc9,
	0x63, 0x68, 0x98, 0x41, 0x92, 0xb8, 0xe6, 0x9a, 0xf2, 0x98, 0xd9, 0xbb, 0x7e, 0xa1, 0xf5, 0x7b,
	0x8c, 0x63, 0x2b, 0x9a, 0x31, 0x73, 0xa2, 0xcb, 0xcc, 0xd2, 0x14, 0xe9, 0x34, 0xf3, 0x4b, 0xa8,
	0x3e, 0x65, 0x8a, 0xf4, 0x1d, 0xe5, 0x7d, 0x3e, 0x60, 0xf6, 0x6e, 0x5e, 0x82, 0x98, 0x0f, 0x97,
	0x35, 0x9c, 0x0c, 0x89, 0x03, 0x5a, 0x9a, 0x1a, 0x9d, 0x74, 0x5e, 0x40, 0x0d, 0xc7, 0x41, 0x97,
	0x89, 0xd2, 0xe4, 0xd8, 0x0b, 0x2e, 0x83, 0x58, 0x46, 0xbf, 0x83, 0x56, 0xd1, 0xa8, 0x92, 0xdb,
	0x8e, 0xb7, 0x6f, 0xb9, 0xe7, 0xed, 0xdd, 0x59, 0x07, 0x9b, 0x0f, 0xaa, 0x75, 0xdd, 0xb0, 0x12,
	0x07, 0x8f, 0x72, 0x37, 0xeb, 0x0c, 0x77, 0x0f, 0x6a, 0xd8, 0xcd, 0xba, 0xc2, 0x2d, 0x75, 0xba,
	0x4e, 0x13, 0x87, 0xd0, 0x30, 0x9d, 0xa9, 0x2b, 0x0f, 0x96, 0xfa, 0xe0, 0xde, 0xad, 0xcb, 0x41,
	0x8b, 0x2f, 0x89, 0xdd, 0xa9, 0x8b, 0x57, 0xa9, 0x73, 0x75, 0xf2, 0x3a, 0x06, 0x58, 0xb4, 0x90,
	0xe4, 0x73, 0x47, 0xaa, 0x9f, 0xef, 0x65, 0x7b, 0x3b, 0xeb, 0x81, 0x96, 0xe3, 0x2b, 0x68, 0xda,
	0xae, 0x92, 0xdc, 0x72, 0xb6, 0x35, 0xa5, 0x66, 0xb5, 0x77, 0x7b, 0x0d, 0x6a, 0x61, 0xd7, 0x76,
	0x83, 0x2e, 0xbb, 0xcb, 0x8d, 0xab, 0xcb, 0xee, 0xb9, 0x96, 0x92, 0x1c, 0x40, 0x5d, 0xff, 0x09,
	0xe1, 0x4a, 0x98, 0xf2, 0x3f, 0x16, 0xbd, 0xcf, 0x2e, 0xc5, 0x18, 0x8b, 0x0f, 0x07, 0x6f, 0xbe,
	0xb8, 0xf2, 0xbf, 0x66, 0x3f, 0x9b, 0xdd, 0x7d, 0xfd, 0xd1, 0xb0, 0xa1, 0x3f, 0xd2, 0xfd, 0xff,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x75, 0xfc, 0x9b, 0x6e, 0x13, 0x00, 0x00,
}
