// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/stellarproject/nebula/agent/v1/agent.proto

package v1 // import "github.com/stellarproject/nebula/agent/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// skipping weak import gogoproto "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"

import time "time"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	Update               bool       `protobuf:"varint,2,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *CreateRequest) GetUpdate() bool {
	if m != nil {
		return m.Update
	}
	return false
}

type DeleteRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{1}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetResponse struct {
	Container            *ContainerInfo `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{3}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetContainer() *ContainerInfo {
	if m != nil {
		return m.Container
	}
	return nil
}

type RestartRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Signal               uint32   `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartRequest) Reset()         { *m = RestartRequest{} }
func (m *RestartRequest) String() string { return proto.CompactTextString(m) }
func (*RestartRequest) ProtoMessage()    {}
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{4}
}
func (m *RestartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartRequest.Unmarshal(m, b)
}
func (m *RestartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartRequest.Marshal(b, m, deterministic)
}
func (dst *RestartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartRequest.Merge(dst, src)
}
func (m *RestartRequest) XXX_Size() int {
	return xxx_messageInfo_RestartRequest.Size(m)
}
func (m *RestartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartRequest proto.InternalMessageInfo

func (m *RestartRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RestartRequest) GetSignal() uint32 {
	if m != nil {
		return m.Signal
	}
	return 0
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{5}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Containers           []*ContainerInfo `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{6}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetContainers() []*ContainerInfo {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ContainerInfo struct {
	ID                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string      `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Status               string      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	IP                   string      `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Cpu                  uint64      `protobuf:"varint,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryUsage          float64     `protobuf:"fixed64,6,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryLimit          float64     `protobuf:"fixed64,7,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	PidUsage             uint64      `protobuf:"varint,8,opt,name=pid_usage,json=pidUsage,proto3" json:"pid_usage,omitempty"`
	PidLimit             uint64      `protobuf:"varint,9,opt,name=pid_limit,json=pidLimit,proto3" json:"pid_limit,omitempty"`
	FsSize               int64       `protobuf:"varint,10,opt,name=fs_size,json=fsSize,proto3" json:"fs_size,omitempty"`
	Config               *Container  `protobuf:"bytes,11,opt,name=config" json:"config,omitempty"`
	Snapshots            []*Snapshot `protobuf:"bytes,12,rep,name=snapshots" json:"snapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContainerInfo) Reset()         { *m = ContainerInfo{} }
func (m *ContainerInfo) String() string { return proto.CompactTextString(m) }
func (*ContainerInfo) ProtoMessage()    {}
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{7}
}
func (m *ContainerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerInfo.Unmarshal(m, b)
}
func (m *ContainerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerInfo.Marshal(b, m, deterministic)
}
func (dst *ContainerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerInfo.Merge(dst, src)
}
func (m *ContainerInfo) XXX_Size() int {
	return xxx_messageInfo_ContainerInfo.Size(m)
}
func (m *ContainerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerInfo proto.InternalMessageInfo

func (m *ContainerInfo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ContainerInfo) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ContainerInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ContainerInfo) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ContainerInfo) GetCpu() uint64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *ContainerInfo) GetMemoryUsage() float64 {
	if m != nil {
		return m.MemoryUsage
	}
	return 0
}

func (m *ContainerInfo) GetMemoryLimit() float64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

func (m *ContainerInfo) GetPidUsage() uint64 {
	if m != nil {
		return m.PidUsage
	}
	return 0
}

func (m *ContainerInfo) GetPidLimit() uint64 {
	if m != nil {
		return m.PidLimit
	}
	return 0
}

func (m *ContainerInfo) GetFsSize() int64 {
	if m != nil {
		return m.FsSize
	}
	return 0
}

func (m *ContainerInfo) GetConfig() *Container {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ContainerInfo) GetSnapshots() []*Snapshot {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

type Snapshot struct {
	ID                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              time.Time `protobuf:"bytes,2,opt,name=created,stdtime" json:"created"`
	Previous             string    `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	FsSize               int64     `protobuf:"varint,4,opt,name=fs_size,json=fsSize,proto3" json:"fs_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{8}
}
func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (dst *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(dst, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Snapshot) GetCreated() time.Time {
	if m != nil {
		return m.Created
	}
	return time.Time{}
}

func (m *Snapshot) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *Snapshot) GetFsSize() int64 {
	if m != nil {
		return m.FsSize
	}
	return 0
}

type RollbackRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackRequest) Reset()         { *m = RollbackRequest{} }
func (m *RollbackRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackRequest) ProtoMessage()    {}
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{9}
}
func (m *RollbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackRequest.Unmarshal(m, b)
}
func (m *RollbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackRequest.Marshal(b, m, deterministic)
}
func (dst *RollbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackRequest.Merge(dst, src)
}
func (m *RollbackRequest) XXX_Size() int {
	return xxx_messageInfo_RollbackRequest.Size(m)
}
func (m *RollbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackRequest proto.InternalMessageInfo

func (m *RollbackRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type RollbackResponse struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RollbackResponse) Reset()         { *m = RollbackResponse{} }
func (m *RollbackResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackResponse) ProtoMessage()    {}
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{10}
}
func (m *RollbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackResponse.Unmarshal(m, b)
}
func (m *RollbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackResponse.Marshal(b, m, deterministic)
}
func (dst *RollbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackResponse.Merge(dst, src)
}
func (m *RollbackResponse) XXX_Size() int {
	return xxx_messageInfo_RollbackResponse.Size(m)
}
func (m *RollbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackResponse proto.InternalMessageInfo

func (m *RollbackResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type StartRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{11}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type StopRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{12}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UpdateRequest struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{13}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type UpdateResponse struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{14}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type CheckpointRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Live                 bool     `protobuf:"varint,3,opt,name=live,proto3" json:"live,omitempty"`
	Exit                 bool     `protobuf:"varint,4,opt,name=exit,proto3" json:"exit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckpointRequest) Reset()         { *m = CheckpointRequest{} }
func (m *CheckpointRequest) String() string { return proto.CompactTextString(m) }
func (*CheckpointRequest) ProtoMessage()    {}
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{15}
}
func (m *CheckpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckpointRequest.Unmarshal(m, b)
}
func (m *CheckpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckpointRequest.Marshal(b, m, deterministic)
}
func (dst *CheckpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointRequest.Merge(dst, src)
}
func (m *CheckpointRequest) XXX_Size() int {
	return xxx_messageInfo_CheckpointRequest.Size(m)
}
func (m *CheckpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointRequest proto.InternalMessageInfo

func (m *CheckpointRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CheckpointRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *CheckpointRequest) GetLive() bool {
	if m != nil {
		return m.Live
	}
	return false
}

func (m *CheckpointRequest) GetExit() bool {
	if m != nil {
		return m.Exit
	}
	return false
}

type CheckpointResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckpointResponse) Reset()         { *m = CheckpointResponse{} }
func (m *CheckpointResponse) String() string { return proto.CompactTextString(m) }
func (*CheckpointResponse) ProtoMessage()    {}
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{16}
}
func (m *CheckpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckpointResponse.Unmarshal(m, b)
}
func (m *CheckpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckpointResponse.Marshal(b, m, deterministic)
}
func (dst *CheckpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointResponse.Merge(dst, src)
}
func (m *CheckpointResponse) XXX_Size() int {
	return xxx_messageInfo_CheckpointResponse.Size(m)
}
func (m *CheckpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointResponse proto.InternalMessageInfo

type RestoreRequest struct {
	Ref                  string   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Live                 bool     `protobuf:"varint,2,opt,name=live,proto3" json:"live,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{17}
}
func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (dst *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(dst, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

func (m *RestoreRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *RestoreRequest) GetLive() bool {
	if m != nil {
		return m.Live
	}
	return false
}

type RestoreResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreResponse) Reset()         { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()    {}
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{18}
}
func (m *RestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResponse.Unmarshal(m, b)
}
func (m *RestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResponse.Marshal(b, m, deterministic)
}
func (dst *RestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResponse.Merge(dst, src)
}
func (m *RestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreResponse.Size(m)
}
func (m *RestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResponse proto.InternalMessageInfo

type MigrateRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Live                 bool     `protobuf:"varint,3,opt,name=live,proto3" json:"live,omitempty"`
	Stop                 bool     `protobuf:"varint,4,opt,name=stop,proto3" json:"stop,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Delete               bool     `protobuf:"varint,6,opt,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateRequest) Reset()         { *m = MigrateRequest{} }
func (m *MigrateRequest) String() string { return proto.CompactTextString(m) }
func (*MigrateRequest) ProtoMessage()    {}
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{19}
}
func (m *MigrateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateRequest.Unmarshal(m, b)
}
func (m *MigrateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateRequest.Marshal(b, m, deterministic)
}
func (dst *MigrateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateRequest.Merge(dst, src)
}
func (m *MigrateRequest) XXX_Size() int {
	return xxx_messageInfo_MigrateRequest.Size(m)
}
func (m *MigrateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateRequest proto.InternalMessageInfo

func (m *MigrateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MigrateRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *MigrateRequest) GetLive() bool {
	if m != nil {
		return m.Live
	}
	return false
}

func (m *MigrateRequest) GetStop() bool {
	if m != nil {
		return m.Stop
	}
	return false
}

func (m *MigrateRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MigrateRequest) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

type MigrateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateResponse) Reset()         { *m = MigrateResponse{} }
func (m *MigrateResponse) String() string { return proto.CompactTextString(m) }
func (*MigrateResponse) ProtoMessage()    {}
func (*MigrateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{20}
}
func (m *MigrateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateResponse.Unmarshal(m, b)
}
func (m *MigrateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateResponse.Marshal(b, m, deterministic)
}
func (dst *MigrateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateResponse.Merge(dst, src)
}
func (m *MigrateResponse) XXX_Size() int {
	return xxx_messageInfo_MigrateResponse.Size(m)
}
func (m *MigrateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateResponse proto.InternalMessageInfo

type Container struct {
	ID        string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image     string     `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Network   string     `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Process   *Process   `protobuf:"bytes,4,opt,name=process" json:"process,omitempty"`
	Mounts    []*Mount   `protobuf:"bytes,5,rep,name=mounts" json:"mounts,omitempty"`
	Resources *Resources `protobuf:"bytes,6,opt,name=resources" json:"resources,omitempty"`
	Gpus      *GPUs      `protobuf:"bytes,7,opt,name=gpus" json:"gpus,omitempty"`
	// map<string, Service> services = 8;
	Configs              map[string]*Config `protobuf:"bytes,9,rep,name=configs" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	Readonly             bool               `protobuf:"varint,10,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Volumes              []*Volume          `protobuf:"bytes,11,rep,name=volumes" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{21}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Container) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Container) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Container) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *Container) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Container) GetGpus() *GPUs {
	if m != nil {
		return m.Gpus
	}
	return nil
}

func (m *Container) GetConfigs() map[string]*Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

func (m *Container) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

func (m *Container) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type Volume struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Rw                   bool     `protobuf:"varint,3,opt,name=rw,proto3" json:"rw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{22}
}
func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (dst *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(dst, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Volume) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Volume) GetRw() bool {
	if m != nil {
		return m.Rw
	}
	return false
}

type Config struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Signal               uint32   `protobuf:"varint,3,opt,name=signal,proto3" json:"signal,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{23}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Config) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Config) GetSignal() uint32 {
	if m != nil {
		return m.Signal
	}
	return 0
}

func (m *Config) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GPUs struct {
	Devices              []int64  `protobuf:"varint,1,rep,packed,name=devices" json:"devices,omitempty"`
	Capabilities         []string `protobuf:"bytes,2,rep,name=capabilities" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPUs) Reset()         { *m = GPUs{} }
func (m *GPUs) String() string { return proto.CompactTextString(m) }
func (*GPUs) ProtoMessage()    {}
func (*GPUs) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{24}
}
func (m *GPUs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPUs.Unmarshal(m, b)
}
func (m *GPUs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPUs.Marshal(b, m, deterministic)
}
func (dst *GPUs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUs.Merge(dst, src)
}
func (m *GPUs) XXX_Size() int {
	return xxx_messageInfo_GPUs.Size(m)
}
func (m *GPUs) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUs.DiscardUnknown(m)
}

var xxx_messageInfo_GPUs proto.InternalMessageInfo

func (m *GPUs) GetDevices() []int64 {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *GPUs) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type Resources struct {
	Cpus                 float64  `protobuf:"fixed64,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory               int64    `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Score                int64    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	NoFile               uint64   `protobuf:"varint,4,opt,name=no_file,json=noFile,proto3" json:"no_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{25}
}
func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (dst *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(dst, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetCpus() float64 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *Resources) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Resources) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Resources) GetNoFile() uint64 {
	if m != nil {
		return m.NoFile
	}
	return 0
}

type Mount struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Options              []string `protobuf:"bytes,4,rep,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{26}
}
func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (dst *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(dst, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Mount) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Mount) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Mount) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type Process struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	Env                  []string `protobuf:"bytes,3,rep,name=env" json:"env,omitempty"`
	Capabilities         []string `protobuf:"bytes,4,rep,name=capabilities" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{27}
}
func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (dst *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(dst, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Process) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Process) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Process) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type User struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{28}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type Assembly struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Assembly) Reset()         { *m = Assembly{} }
func (m *Assembly) String() string { return proto.CompactTextString(m) }
func (*Assembly) ProtoMessage()    {}
func (*Assembly) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{29}
}
func (m *Assembly) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assembly.Unmarshal(m, b)
}
func (m *Assembly) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assembly.Marshal(b, m, deterministic)
}
func (dst *Assembly) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assembly.Merge(dst, src)
}
func (m *Assembly) XXX_Size() int {
	return xxx_messageInfo_Assembly.Size(m)
}
func (m *Assembly) XXX_DiscardUnknown() {
	xxx_messageInfo_Assembly.DiscardUnknown(m)
}

var xxx_messageInfo_Assembly proto.InternalMessageInfo

func (m *Assembly) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Assembly) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type ApplyRequest struct {
	Assemblies           []*Assembly `protobuf:"bytes,1,rep,name=assemblies" json:"assemblies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_90705af462f8554b, []int{30}
}
func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(dst, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetAssemblies() []*Assembly {
	if m != nil {
		return m.Assemblies
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "io.stellarproject.agent.v1.CreateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "io.stellarproject.agent.v1.DeleteRequest")
	proto.RegisterType((*GetRequest)(nil), "io.stellarproject.agent.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "io.stellarproject.agent.v1.GetResponse")
	proto.RegisterType((*RestartRequest)(nil), "io.stellarproject.agent.v1.RestartRequest")
	proto.RegisterType((*ListRequest)(nil), "io.stellarproject.agent.v1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "io.stellarproject.agent.v1.ListResponse")
	proto.RegisterType((*ContainerInfo)(nil), "io.stellarproject.agent.v1.ContainerInfo")
	proto.RegisterType((*Snapshot)(nil), "io.stellarproject.agent.v1.Snapshot")
	proto.RegisterType((*RollbackRequest)(nil), "io.stellarproject.agent.v1.RollbackRequest")
	proto.RegisterType((*RollbackResponse)(nil), "io.stellarproject.agent.v1.RollbackResponse")
	proto.RegisterType((*StartRequest)(nil), "io.stellarproject.agent.v1.StartRequest")
	proto.RegisterType((*StopRequest)(nil), "io.stellarproject.agent.v1.StopRequest")
	proto.RegisterType((*UpdateRequest)(nil), "io.stellarproject.agent.v1.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "io.stellarproject.agent.v1.UpdateResponse")
	proto.RegisterType((*CheckpointRequest)(nil), "io.stellarproject.agent.v1.CheckpointRequest")
	proto.RegisterType((*CheckpointResponse)(nil), "io.stellarproject.agent.v1.CheckpointResponse")
	proto.RegisterType((*RestoreRequest)(nil), "io.stellarproject.agent.v1.RestoreRequest")
	proto.RegisterType((*RestoreResponse)(nil), "io.stellarproject.agent.v1.RestoreResponse")
	proto.RegisterType((*MigrateRequest)(nil), "io.stellarproject.agent.v1.MigrateRequest")
	proto.RegisterType((*MigrateResponse)(nil), "io.stellarproject.agent.v1.MigrateResponse")
	proto.RegisterType((*Container)(nil), "io.stellarproject.agent.v1.Container")
	proto.RegisterMapType((map[string]*Config)(nil), "io.stellarproject.agent.v1.Container.ConfigsEntry")
	proto.RegisterType((*Volume)(nil), "io.stellarproject.agent.v1.Volume")
	proto.RegisterType((*Config)(nil), "io.stellarproject.agent.v1.Config")
	proto.RegisterType((*GPUs)(nil), "io.stellarproject.agent.v1.GPUs")
	proto.RegisterType((*Resources)(nil), "io.stellarproject.agent.v1.Resources")
	proto.RegisterType((*Mount)(nil), "io.stellarproject.agent.v1.Mount")
	proto.RegisterType((*Process)(nil), "io.stellarproject.agent.v1.Process")
	proto.RegisterType((*User)(nil), "io.stellarproject.agent.v1.User")
	proto.RegisterType((*Assembly)(nil), "io.stellarproject.agent.v1.Assembly")
	proto.RegisterType((*ApplyRequest)(nil), "io.stellarproject.agent.v1.ApplyRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	// lifecycle
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*types.Empty, error)
	// info
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// upgrades
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	// migration
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error)
	// terra
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*types.Empty, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Restart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Rollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Checkpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error) {
	out := new(MigrateResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Migrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.agent.v1.Agent/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	// lifecycle
	Create(context.Context, *CreateRequest) (*types.Empty, error)
	Delete(context.Context, *DeleteRequest) (*types.Empty, error)
	Start(context.Context, *StartRequest) (*types.Empty, error)
	Stop(context.Context, *StopRequest) (*types.Empty, error)
	Restart(context.Context, *RestartRequest) (*types.Empty, error)
	// info
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	// upgrades
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	// migration
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	Migrate(context.Context, *MigrateRequest) (*MigrateResponse, error)
	// terra
	Apply(context.Context, *ApplyRequest) (*types.Empty, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Restart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Rollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Checkpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Migrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.agent.v1.Agent/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.stellarproject.agent.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Agent_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Agent_Delete_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Agent_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Agent_Stop_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Agent_Restart_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Agent_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Agent_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Agent_Update_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _Agent_Rollback_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _Agent_Checkpoint_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Agent_Restore_Handler,
		},
		{
			MethodName: "Migrate",
			Handler:    _Agent_Migrate_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Agent_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/stellarproject/nebula/agent/v1/agent.proto",
}

func init() {
	proto.RegisterFile("github.com/stellarproject/nebula/agent/v1/agent.proto", fileDescriptor_agent_90705af462f8554b)
}

var fileDescriptor_agent_90705af462f8554b = []byte{
	// 1445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0x0e, 0x45, 0x3d, 0x47, 0x92, 0x93, 0x2c, 0x82, 0x94, 0x50, 0x0e, 0x56, 0xd8, 0x3c, 0x94,
	0x47, 0x25, 0xc4, 0x4d, 0x8b, 0xf4, 0x91, 0xa2, 0xb1, 0x9d, 0x1a, 0x46, 0x13, 0x20, 0x58, 0xc7,
	0x69, 0xd3, 0x43, 0x0d, 0x4a, 0x5a, 0xd1, 0x5b, 0x53, 0x5c, 0x96, 0xbb, 0x54, 0xaa, 0xfc, 0x83,
	0xf6, 0xd4, 0x5b, 0x0f, 0xfd, 0x43, 0x3d, 0xf6, 0x17, 0xa4, 0x40, 0xff, 0x48, 0x8b, 0x7d, 0x50,
	0xa2, 0xec, 0x88, 0x52, 0x80, 0xdc, 0x66, 0x96, 0xf3, 0xda, 0xd9, 0x99, 0x6f, 0x67, 0x09, 0x9f,
	0xf8, 0x54, 0x1c, 0x27, 0xfd, 0xee, 0x80, 0x8d, 0x7b, 0x5c, 0x90, 0x20, 0xf0, 0xe2, 0x28, 0x66,
	0x3f, 0x91, 0x81, 0xe8, 0x85, 0xa4, 0x9f, 0x04, 0x5e, 0xcf, 0xf3, 0x49, 0x28, 0x7a, 0x93, 0x7b,
	0x9a, 0xe8, 0x46, 0x31, 0x13, 0x0c, 0xb5, 0x28, 0xeb, 0x2e, 0x8a, 0x77, 0xf5, 0xe7, 0xc9, 0xbd,
	0xd6, 0x25, 0x9f, 0xf9, 0x4c, 0x89, 0xf5, 0x24, 0xa5, 0x35, 0x5a, 0x57, 0x7c, 0xc6, 0xfc, 0x80,
	0xf4, 0x14, 0xd7, 0x4f, 0x46, 0x3d, 0x32, 0x8e, 0xc4, 0xd4, 0x7c, 0xdc, 0x3c, 0xfd, 0x51, 0xd0,
	0x31, 0xe1, 0xc2, 0x1b, 0x47, 0x5a, 0xc0, 0x0d, 0xa0, 0xb9, 0x13, 0x13, 0x4f, 0x10, 0x4c, 0x7e,
	0x4e, 0x08, 0x17, 0x68, 0x07, 0x6a, 0x03, 0x16, 0x0a, 0x8f, 0x86, 0x24, 0x76, 0xac, 0xb6, 0xd5,
	0xa9, 0x6f, 0x5d, 0xef, 0x2e, 0x0f, 0xaa, 0xbb, 0x93, 0x0a, 0xe3, 0xb9, 0x1e, 0xba, 0x0c, 0xe5,
	0x24, 0x1a, 0x7a, 0x82, 0x38, 0x85, 0xb6, 0xd5, 0xa9, 0x62, 0xc3, 0xb9, 0x37, 0xa1, 0xb9, 0x4b,
	0x02, 0x32, 0xf7, 0x76, 0x19, 0x0a, 0x74, 0xa8, 0xdc, 0xd4, 0xb6, 0xcb, 0xff, 0xbe, 0xd9, 0x2c,
	0xec, 0xef, 0xe2, 0x02, 0x1d, 0xba, 0xd7, 0x00, 0xf6, 0x88, 0x58, 0x25, 0xf5, 0x02, 0xea, 0x4a,
	0x8a, 0x47, 0x2c, 0xe4, 0x04, 0xed, 0x9d, 0x0d, 0xfd, 0xd6, 0x5a, 0xa1, 0xef, 0x87, 0x23, 0x96,
	0x09, 0xdf, 0xfd, 0x1a, 0x36, 0xb0, 0xcc, 0x52, 0xbc, 0x2a, 0x02, 0xb9, 0x51, 0x4e, 0xfd, 0xd0,
	0x0b, 0xd4, 0x46, 0x9b, 0xd8, 0x70, 0x6e, 0x13, 0xea, 0x4f, 0x28, 0x4f, 0xd5, 0xdd, 0x97, 0xd0,
	0xd0, 0xac, 0x89, 0x74, 0x1f, 0x60, 0xe6, 0x8d, 0x3b, 0x56, 0xdb, 0x7e, 0xb7, 0x50, 0x33, 0xca,
	0xee, 0x9f, 0x36, 0x34, 0x17, 0xbe, 0x2e, 0x8d, 0xf5, 0x12, 0x94, 0xe8, 0xd8, 0xf3, 0xf5, 0x99,
	0xd4, 0xb0, 0x66, 0xd4, 0x0e, 0x84, 0x27, 0x12, 0xee, 0xd8, 0x6a, 0xd9, 0x70, 0xca, 0x4a, 0xe4,
	0x14, 0x33, 0x56, 0x9e, 0xe1, 0x02, 0x8d, 0xd0, 0x05, 0xb0, 0x07, 0x51, 0xe2, 0x94, 0xda, 0x56,
	0xa7, 0x88, 0x25, 0x89, 0xae, 0x42, 0x63, 0x4c, 0xc6, 0x2c, 0x9e, 0x1e, 0x25, 0x5c, 0x9a, 0x2f,
	0xb7, 0xad, 0x8e, 0x85, 0xeb, 0x7a, 0xed, 0x50, 0x2e, 0x65, 0x44, 0x02, 0x3a, 0xa6, 0xc2, 0xa9,
	0x64, 0x45, 0x9e, 0xc8, 0x25, 0x74, 0x05, 0x6a, 0x11, 0x1d, 0x1a, 0x13, 0x55, 0x65, 0xbd, 0x1a,
	0xd1, 0xa1, 0xd6, 0x37, 0x1f, 0xb5, 0x72, 0x6d, 0xf6, 0x51, 0x6b, 0x7e, 0x00, 0x95, 0x11, 0x3f,
	0xe2, 0xf4, 0x35, 0x71, 0xa0, 0x6d, 0x75, 0x6c, 0x5c, 0x1e, 0xf1, 0x03, 0xfa, 0x9a, 0xa0, 0x87,
	0x50, 0x1e, 0xb0, 0x70, 0x44, 0x7d, 0xa7, 0xfe, 0x2e, 0x75, 0x6c, 0x94, 0xd0, 0x36, 0xd4, 0x78,
	0xe8, 0x45, 0xfc, 0x98, 0x09, 0xee, 0x34, 0xd4, 0x19, 0x5d, 0xcb, 0xb3, 0x70, 0x60, 0x84, 0xf1,
	0x5c, 0xcd, 0xfd, 0xc3, 0x82, 0x6a, 0xba, 0xbe, 0xf4, 0x60, 0xbe, 0x82, 0xca, 0x40, 0xf5, 0xe0,
	0x50, 0x1d, 0x4d, 0x7d, 0xab, 0xd5, 0xd5, 0x6d, 0xdb, 0x4d, 0xdb, 0xb6, 0xfb, 0x3c, 0x6d, 0xdb,
	0xed, 0xea, 0x5f, 0x6f, 0x36, 0xcf, 0xfd, 0xfe, 0xcf, 0xa6, 0x85, 0x53, 0x25, 0xd4, 0x82, 0x6a,
	0x14, 0x93, 0x09, 0x65, 0xb3, 0x43, 0x9c, 0xf1, 0xd9, 0xe4, 0x14, 0xb3, 0xc9, 0x71, 0x6f, 0xc1,
	0x79, 0xcc, 0x82, 0xa0, 0xef, 0x0d, 0x4e, 0x56, 0xb5, 0xd9, 0x77, 0x70, 0x61, 0x2e, 0x6a, 0x2a,
	0xf8, 0x7d, 0xc0, 0x84, 0x7b, 0x03, 0x1a, 0x07, 0x6b, 0x74, 0x99, 0x7b, 0x1d, 0xea, 0x07, 0x82,
	0x45, 0xab, 0xc4, 0x9e, 0x43, 0xf3, 0x50, 0xe1, 0xcc, 0xfb, 0xc4, 0x32, 0xf7, 0x10, 0x36, 0x52,
	0xab, 0xef, 0x73, 0xef, 0x04, 0x2e, 0xee, 0x1c, 0x93, 0xc1, 0x49, 0xc4, 0x68, 0xb8, 0x12, 0x66,
	0x2e, 0x80, 0x1d, 0x93, 0x91, 0x69, 0x5c, 0x49, 0x22, 0x04, 0xc5, 0x80, 0x4e, 0x88, 0x3a, 0xef,
	0x2a, 0x56, 0xb4, 0x5c, 0x23, 0xbf, 0x50, 0xa1, 0x0e, 0xba, 0x8a, 0x15, 0xed, 0x5e, 0x02, 0x94,
	0x75, 0xa3, 0x77, 0xe0, 0x7e, 0xaa, 0x01, 0x8e, 0xc5, 0xb3, 0x54, 0x19, 0x0f, 0xd6, 0x59, 0x0f,
	0x85, 0xb9, 0x07, 0xf7, 0x22, 0x9c, 0x9f, 0xe9, 0x19, 0x53, 0xbf, 0x59, 0xb0, 0xf1, 0x94, 0xfa,
	0xb1, 0xb7, 0x12, 0xd4, 0xd7, 0xdf, 0x05, 0x17, 0x2c, 0x4a, 0x77, 0x21, 0x69, 0xb4, 0x01, 0x05,
	0xc1, 0x14, 0xe6, 0xd4, 0x70, 0x41, 0x48, 0x88, 0x2b, 0x0f, 0xd5, 0x3d, 0xa2, 0xc0, 0xa6, 0x8a,
	0x0d, 0x27, 0xe3, 0x9b, 0xc5, 0x62, 0xe2, 0xfb, 0xbb, 0x08, 0xb5, 0x9d, 0xcc, 0xc5, 0xf4, 0x2e,
	0xd8, 0xe8, 0x40, 0x25, 0x24, 0xe2, 0x15, 0x8b, 0x4f, 0x4c, 0x5f, 0xa5, 0x2c, 0x7a, 0x08, 0x95,
	0x28, 0x66, 0x03, 0xc2, 0xb9, 0x8a, 0xb3, 0xbe, 0xf5, 0x61, 0x5e, 0x01, 0x3c, 0xd3, 0xa2, 0x38,
	0xd5, 0x41, 0x9f, 0x41, 0x79, 0xcc, 0x92, 0x50, 0x70, 0xa7, 0xa4, 0x70, 0xe5, 0x6a, 0x9e, 0xf6,
	0x53, 0x29, 0x89, 0x8d, 0x82, 0x2c, 0xbe, 0x98, 0x70, 0x96, 0xc4, 0x03, 0xc2, 0xd5, 0xee, 0x57,
	0x14, 0x1f, 0x4e, 0x85, 0xf1, 0x5c, 0x0f, 0xdd, 0x87, 0xa2, 0x1f, 0x25, 0x5c, 0xe1, 0x70, 0x7d,
	0xab, 0x9d, 0xa7, 0xbf, 0xf7, 0xec, 0x90, 0x63, 0x25, 0x8d, 0x9e, 0x40, 0x45, 0x43, 0x23, 0x77,
	0x6a, 0x2a, 0xec, 0xad, 0xb5, 0xaa, 0x5e, 0x52, 0x52, 0xe9, 0x71, 0x28, 0xe2, 0x29, 0x4e, 0x4d,
	0x48, 0xd4, 0x8a, 0x89, 0x37, 0x64, 0x61, 0x30, 0x55, 0xb8, 0x5d, 0xc5, 0x33, 0x1e, 0x7d, 0x09,
	0x95, 0x09, 0x0b, 0x92, 0x31, 0xe1, 0x4e, 0x5d, 0x79, 0x72, 0xf3, 0x3c, 0xbd, 0x50, 0xa2, 0x38,
	0x55, 0x69, 0xfd, 0x08, 0x8d, 0xac, 0x4b, 0x59, 0x77, 0x27, 0x64, 0x9a, 0xd6, 0xf6, 0x09, 0x99,
	0xa2, 0x07, 0x50, 0x9a, 0x78, 0x41, 0x42, 0x0c, 0xde, 0xba, 0x2b, 0xf6, 0x31, 0xa2, 0x3e, 0xd6,
	0x0a, 0x9f, 0x17, 0x1e, 0x58, 0x2e, 0x86, 0xb2, 0x76, 0xb9, 0xb4, 0x9c, 0xda, 0x50, 0x1f, 0x12,
	0x2e, 0x68, 0xe8, 0x09, 0xca, 0x42, 0x53, 0x54, 0xd9, 0x25, 0x59, 0xd1, 0xf1, 0x2b, 0x53, 0xf7,
	0x85, 0xf8, 0x95, 0x3b, 0x82, 0xb2, 0x76, 0x24, 0xeb, 0x3f, 0xf2, 0xc4, 0xb1, 0x09, 0x57, 0xd1,
	0xea, 0x92, 0x56, 0x47, 0x67, 0x4c, 0x19, 0x2e, 0x33, 0x7e, 0xd8, 0xd9, 0xf1, 0x43, 0x16, 0xae,
	0x44, 0x1a, 0x12, 0x6a, 0x30, 0xa8, 0xe1, 0x94, 0x75, 0x77, 0xa1, 0x28, 0x4f, 0x54, 0x4a, 0x0c,
	0xc9, 0x84, 0xca, 0x22, 0x92, 0xe3, 0x87, 0x8d, 0x53, 0x16, 0xb9, 0xd0, 0x18, 0x78, 0x91, 0xd7,
	0xa7, 0x01, 0x15, 0x94, 0x70, 0xa7, 0xd0, 0xb6, 0x3b, 0x35, 0xbc, 0xb0, 0xe6, 0x8e, 0xa0, 0x36,
	0xab, 0x2b, 0x19, 0xf0, 0x40, 0x16, 0x93, 0xa5, 0x2e, 0x75, 0x45, 0xcb, 0xc0, 0xf4, 0xe5, 0xae,
	0x02, 0xb6, 0xb1, 0xe1, 0x64, 0x9f, 0xf1, 0x01, 0x8b, 0x75, 0xc7, 0xdb, 0x58, 0x33, 0xf2, 0x92,
	0x0a, 0xd9, 0xd1, 0x88, 0x06, 0xfa, 0x92, 0x2a, 0xe2, 0x72, 0xc8, 0xbe, 0xa1, 0x01, 0x71, 0x19,
	0x94, 0x54, 0xf5, 0x4b, 0x1f, 0x62, 0x1a, 0x91, 0x34, 0x29, 0x92, 0x5e, 0x9a, 0x94, 0x53, 0xc9,
	0xb7, 0xcf, 0x26, 0xdf, 0x81, 0x0a, 0x8b, 0x24, 0x25, 0xbb, 0x57, 0xee, 0x2e, 0x65, 0xdd, 0x5f,
	0x2d, 0xa8, 0x98, 0x6e, 0x95, 0x4d, 0x92, 0xf0, 0x19, 0xc2, 0xe7, 0x36, 0xc9, 0x21, 0x27, 0x31,
	0x56, 0xd2, 0x32, 0x52, 0x2f, 0xf6, 0xd3, 0xb4, 0x29, 0x5a, 0x16, 0x20, 0x09, 0x27, 0x8e, 0xad,
	0x96, 0x24, 0x79, 0x26, 0xc9, 0xc5, 0xb7, 0x24, 0xf9, 0x36, 0x14, 0xa5, 0x5d, 0xa9, 0x9d, 0x98,
	0x2a, 0x6b, 0x62, 0x49, 0xca, 0x15, 0x9f, 0x0e, 0xcd, 0xc8, 0x29, 0x49, 0xf7, 0x3e, 0x54, 0x1f,
	0x71, 0x4e, 0xc6, 0xfd, 0x60, 0x2a, 0x23, 0x08, 0xbd, 0xf1, 0x2c, 0x57, 0x92, 0x7e, 0x3b, 0xbe,
	0xb9, 0xcf, 0xa1, 0xf1, 0x28, 0x8a, 0x82, 0x69, 0x0a, 0xdc, 0xbb, 0x00, 0x9e, 0xb6, 0x42, 0x49,
	0x3a, 0x96, 0xe6, 0x8e, 0x3c, 0xa9, 0x4f, 0x9c, 0xd1, 0xdb, 0xfa, 0xaf, 0x0a, 0xa5, 0x47, 0x52,
	0x02, 0x7d, 0x0b, 0x65, 0xfd, 0xb8, 0x40, 0xf9, 0xc3, 0x6d, 0xf6, 0x01, 0xd2, 0xba, 0x7c, 0x66,
	0xf8, 0x79, 0x2c, 0x1f, 0x34, 0xd2, 0x98, 0x7e, 0x3b, 0xe4, 0x1b, 0x5b, 0x78, 0x5f, 0x2c, 0x35,
	0xb6, 0x0f, 0x25, 0x35, 0x79, 0xa0, 0x4e, 0xee, 0x44, 0x97, 0x19, 0x4e, 0x96, 0x9a, 0xda, 0x83,
	0xa2, 0x1c, 0x4e, 0xd0, 0xcd, 0x7c, 0x4b, 0xb3, 0xf1, 0x65, 0xa9, 0xa1, 0xa7, 0x50, 0x31, 0xaf,
	0x0e, 0x74, 0x7b, 0x05, 0xa2, 0xaf, 0x13, 0xd7, 0x0b, 0xb0, 0xf7, 0x88, 0x40, 0x37, 0x72, 0xc1,
	0x7d, 0xf6, 0xc6, 0x6a, 0xdd, 0x5c, 0x29, 0x67, 0xa6, 0x9f, 0x97, 0x50, 0x94, 0x6f, 0x99, 0xfc,
	0xfd, 0x66, 0x1e, 0x3f, 0xad, 0xce, 0x6a, 0x41, 0x63, 0xfa, 0x08, 0xca, 0x7a, 0xd4, 0xca, 0x3f,
	0xe2, 0x85, 0x21, 0xaf, 0x75, 0x7b, 0x1d, 0x51, 0xe3, 0x80, 0x40, 0x35, 0x9d, 0x64, 0xd1, 0x9d,
	0xdc, 0x1c, 0x2f, 0x8e, 0xc6, 0xad, 0xbb, 0xeb, 0x09, 0x1b, 0x37, 0x27, 0x00, 0xf3, 0xa1, 0x0b,
	0x7d, 0x94, 0x5b, 0xfb, 0xa7, 0x67, 0xc0, 0x56, 0x77, 0x5d, 0x71, 0xe3, 0xac, 0xaf, 0xcb, 0x46,
	0xe2, 0xe8, 0xca, 0xb2, 0x99, 0x0f, 0x7c, 0xad, 0x3b, 0x6b, 0xc9, 0xce, 0x7d, 0x98, 0xb9, 0x2a,
	0xdf, 0xc7, 0xe2, 0x20, 0x98, 0xef, 0xe3, 0xd4, 0xa0, 0x26, 0x5b, 0x52, 0x81, 0x51, 0x7e, 0x4b,
	0x66, 0xf1, 0x6a, 0x59, 0xe9, 0x6f, 0x77, 0x7f, 0xb8, 0xbb, 0xf6, 0xdf, 0x97, 0x2f, 0x26, 0xf7,
	0xbe, 0x3f, 0xd7, 0x2f, 0x2b, 0x0b, 0x1f, 0xff, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x7d, 0xb5,
	0x16, 0xb6, 0x11, 0x00, 0x00,
}
